# Language Detector
# Languages can be found here: https://minecraft.fandom.com/wiki/Language#Languages
# Language Codes (en) and Locale Codes (en-us) are supported.
# Use lowercase notation with dashes, not underscores (Do en-us, not en_US).
supported-languages:
  - en-us
# Uses MiniMessage formatting (https://webui.adventure.kyori.net/)
# Supported placeholders are:
# - Player Language: <playerlang>
# - Player Locale: <playerlocale>
kick-message: "<red>You have been kicked from the server.\n<yellow>Your language is not set to a supported language.\n<gray>Your language is: <playerlang> (<playerlocale>)"
